### ISSUE TITLE
Not an Issue - Love this Driver

### ISSUE THREAD

**Issue by johnsmith80** [ivanovborislav/rtl8188eu#2]
I like the driver since Its rtl8188eu for TP Link TL-WN722N working on latest kernel 5.18.x and the best part was LED was working, at least it has a job now to blink like how the v1 does. Great.

**Comment by ivanovborislav** [comment]
Thank you for your great feedback!

**Comment by MatzFan** [comment]
Just want to express my appreciation too. My venerable TP Link TL-WN725N was suffering really slow speeds on upgrade to Ubuntu 22.04 and with this driver works perfectly again, even with 22.10 and kernel 5.19. Awesome.

**Comment by ivanovborislav** [comment]
Thank you for your feedback!

**Comment by wyatt** [comment]
Likewise - this driver works amazing and your documentation is great! I spend many hours trying to get this to work, and your driver finally did it 🥳
