### ISSUE TITLE
Adapter not recognized after upgrade to Kernel 5.19.0.26

### ISSUE THREAD

**Issue by MatzFan** [ivanovborislav/rtl8188eu#9]
Yesterday I upgraded to kernel 5.19.0.26-generic and after reboot my TP Link TL-WN725N was not recognized. It has worked perfectly with Kernel 5.19 until now, including the latest patch release 5.19.0-23-generic.

I checked it is not an adapter failure after trying it on an old Mac running OS 10.13 - it still works fine.

System:
Ubuntu 22.10
TP Link TL-WN725N (V1)

**Comment by ivanovborislav** [comment]
Hi!
Recompile and install again please!

**Comment by MatzFan** [comment]
Awesome, fixed, many thanks.

**Comment by ivanovborislav** [comment]
You are welcome!
